### ISSUE TITLE
language names are not language descriptors

### ISSUE THREAD

**Issue by karlkleinpaste** [crosswire/xiphos#1000]
long parenthesized descriptions of languages, usually advertising a nationality, are not appropriate for ui/languages. the names are to be short and to the point. long qualifiers are unnecessary as language names, and their presence makes for huge gaping empty holes in the use of window real estate because of the otherwise short names used everywhere else, screwing up the appearance of module displays.

**Comment by LAfricain** [comment]
It is true that it is not very pretty nor very practical this long descriptions of the language. I also hesitated to delete it rather than translate it. The only problem, at least for African languages is that the same language can be in different countries and have little nuance, hence the addition of the country in parenthesis. In the case of Kikongo it is present both in the DRC and the Congo Brazzaville.

**Comment by karlkleinpaste** [comment]
then perhaps a single "(Congo)" would be appropriate; there were already some like that, which i left alone. i'm unaware of the precise distinctions to be made here, but having looked through a couple module displays, the hole in the mod.mgr was all too obvious. the full legal name of a country of origin is just more than the display can accept and still look reasonable.

**Comment by LAfricain** [comment]
No Congo is not enough, when you had Congo that means Congo Brazzaville. For Democratic Republic of Congo I propose you: RDC. This should be very OK.
For République centrafricaine, just Centreafrique.
