### ISSUE TITLE
Create release and post build artifacts on git tags

### ISSUE THREAD

**Issue by alerque** [crosswire/xiphos#1001]
Per [discussion here](https://github.com/crosswire/xiphos/pull/979#issuecomment-614777832), we should setup a Github Action CI runner than builds the appropriate release formats and posts the artifacts to a Github Release whenever new tags are pushed.

Feel free to assign this issue to me so I don't forget.

**Comment by greg-hellings** [comment]
I have this mostly working in my fork (did the dev on "master" in that repo). Not quite done. But if you're going to tackle this before I circle back around to it, know that you don't have to reinvent the wheel (but you will want to squash merge).

I'll have lots of free time this weekend, but I don't know what your schedule will look like.

**Comment by greg-hellings** [comment]
Current hold up: no working editor in Ubuntu.

They have completely excised GtkHTML, and WebKit 1, and changes in WebKit 2 since webkitgtk 2.24 have rendered even what we do have for WK2 editors completely non-functional. Also, no working Windows build _at all_ currently.

**Comment by karlkleinpaste** [comment]
i'm wondering about closing this, as everything of consequence that was in question is done. the windows build is back. the editor is what it is, we're not going to fix that immediately and i will open a separate issue about that. so yes, i'm closing this one because all the automated build stuff that was really in question has been handled so well.
