### ISSUE TITLE
Please provide italics rendering for catchWord & rdg elements in OSIS footnotes

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#1017]
Please to the **OSIS 2.1.1 Reference** for the OSIS elements that are allowed within **note** elements.

If the words enclosed within either a **catchWord** element or a **rdg** element were to be rendered with *italics*, they would then be distinguishable from other note text.

NB. The CrossWire KJV module v2.9 already contains this OSIS markup.

**Comment by DavidHaslam** [comment]
Aside: Despite it being two years since its last release, the **PocketSword** app already has this feature.

I can readily supply a **screenshot** if this would be of any help.

**Comment by karlkleinpaste** [comment]
this is a job for the sword filters, not for xiphos.

generally speaking, xiphos asks the engine for content, and pastes what comes back into the xhtml widget. how (indeed, whether) the engine does that is up to troy. if there's an incomplete aspect of the osis-to-xhtml filtering, it needs to be corrected there.

if PS has this ability, it's because of a locally-hacked (by nic) version of sword, or nic wrote an html post-delivery hack.
