### ISSUE TITLE
Indexing NETfree crashes Xiphos

### ISSUE THREAD

**Issue by marawuti** [crosswire/xiphos#1047]
Attempted to index NETfree 1.0.1.  Xiphos aborts.

**Comment by karlkleinpaste** [comment]
it would have been good to know what platform you were using.

both the command line indexer mkfastmod and xiphos itself have no problem with this under linux.  however, i see that both mkfastmod and xiphos die against NETfree.  the xiphos crash gives me enough information to see that the death occurs in the sword lib itself, in function sword::TreeKey::getIndex().  so it appears that the windows build has a problem not seen in a linux build.

since it's not a xiphos problem proper -- xiphos is, in this regard, strictly a client program using an outside library -- i'm closing this, but will report it upstream to the library folks. thanx.
