### ISSUE TITLE
xiphos cannot find image display program

### ISSUE THREAD

**Issue by jbbacher** [crosswire/xiphos#1053]
I receive this pop-up: (xiphos cannot find image display program) each time i try to enlarge a map from any of the maps modules i've tried.  I'm using Xiphos 4.1.0 (gtk3 webkit2) from flatpak on POP-OS! 20.04.

**Comment by karlkleinpaste** [comment]
flatpak builds of xiphos are a scourge on humanity and we can't support them. we don't know builds them and we aren't responsible for them.

popos is an ubuntu derivative. see the ppa ref'd in https://github.com/crosswire/xiphos/releases/tag/4.2.1 and install from there.

the underlying problem is that your miscegenated flatpak lives in an isolated universe where it cannot find such necessary trivialities as xdg_open.
