### ISSUE TITLE
Morphology not read at all

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#1068]
In the new LXX module (in the beta repo) The morphology is shown but not displayed in the packard dictionary when you pass or click on it with the mouse. I tried different separators, the + the space the -. I don't know what is wrong: this is an example of the osis file:
```
<verse osisID="Gen.1.1">
<w lemma="strong:G1722 lex:ἐν" morph="packard:P" xlit="betacode:E)N">ἐν</w> <w lemma="strong:G746 lex:ἀρχή" morph="packard:N1+DSF" xlit="betacode:A)RXH=|">ἀρχῇ</w> <w lemma="strong:G4160 lex:ποιέω" morph="packard:VAI+AAI3S" xlit="betacode:E)POI/HSEN">ἐποίησεν</w> <w lemma="strong:G3588 lex:ὁ" morph="packard:RA+NSM" xlit="betacode:O(">ὁ</w> <w lemma="strong:G2316 lex:θεός" morph="packard:N2+NSM" xlit="betacode:QEO\S">θεὸς</w> <w lemma="strong:G3588 lex:ὁ" morph="packard:RA+ASM" xlit="betacode:TO\N">τὸν</w> <w lemma="strong:G3772 lex:οὐρανός" morph="packard:N2+ASM" xlit="betacode:OU)RANO\N">οὐρανὸν</w> <w lemma="strong:G2532 lex:καί" morph="packard:C" xlit="betacode:KAI\">καὶ</w> <w lemma="strong:G3588 lex:ὁ" morph="packard:RA+ASF" xlit="betacode:TH\N">τὴν</w> <w lemma="strong:G1093 lex:γῆ" morph="packard:N1+ASF" xlit="betacode:GH=N">γῆν</w>
```
Is my osis faulty? Because the 2TGreek module works perfectly with the morphology (only if we have one letter, then xiphos displays nothing)

Thank yo for help.

**Comment by pierre-amadio** [comment]
This modification makes the morph code be interpreted:

diff --git a/src/main/url.cc b/src/main/url.cc
index c71defc9..50607dba 100644
--- a/src/main/url.cc
+++ b/src/main/url.cc
@@ -313,6 +313,7 @@ static gint show_morph(const char *module_name,
        if (!strcmp(stype, "Greek") ||
            strstr(stype, "x-Robinson") ||
            strstr(stype, "robinson") ||
+           strstr(stype, "packard") ||
            strstr(stype, "Robinson")) {
                if (backend->get_key_testament(module_name,
                                               settings.currentverse) == 2) {

However, because of  https://tracker.crosswire.org/browse/MOD-397 , the resulting interpretation is wrong.
The next step is to have packard module that expect dash as separator (instead of space), then the above patch should make morph information visible.

**Comment by LAfricain** [comment]
Thank you Pierre for your help!
