### ISSUE TITLE
Add new vi.po

### ISSUE THREAD

**Issue by nghiengnghieng** [crosswire/xiphos#1073]
Hi there,
I just finished the Vietnamese translation
[vi.zip](https://github.com/crosswire/xiphos/files/5860915/vi.zip)
Please add it in the next version, thanks

**Comment by karlkleinpaste** [comment]
a big thank you for this.

**Comment by alerque** [comment]
There isn't much work collected yet to make a new major release, but a complete new language from zero to ready-to-use might be a good enough justification for a minor or patch release just so that word goes out and this can easily be used without sitting around forever before a release is eventually pushed through for other reasons.

**Comment by LAfricain** [comment]
About translation, if someone can update the po files it would be nice.

**Comment by alerque** [comment]
@LAfricain Can you be more specific? The `vi.po` file was updated in 66392F5, is that not what needed to happen? Or are you talking about other languages?

**Comment by LAfricain** [comment]
It's in general. The current po files are not completely updated. Some 
strings are missing. I tried tu use the tools proposed for an update but 
it didn't work.

Le 24/01/2021 à 09:32, Caleb Maclennan a écrit :

**Comment by alerque** [comment]
Okay. Maybe better open a new issue to track that since this one is (rightly) closed.
