### ISSUE TITLE
Display Image in TEI module

### ISSUE THREAD

**Issue by JohanMa** [crosswire/xiphos#1086]
I want to display images in a TEI dictionary module, but receive an error message "An image's file size could not be determined. Xiphos cannot resize images to fit window.

The TEI text is:
<entryFree sortKey="A. THE RED SEA CROSSING">
<figure>
 <graphic url="Red Sea Crossing.jpg"/>
 <head>The Red Sea Crossing
<lb/><figDesc><xr type="Bible"><ref osisRef="TS2020_Beta_4:Exo.14">Exo 14</ref>, <ref osisRef="TS2020_Beta_4:Num.33">Num 33</ref></xr></figDesc>
<lb/><lb/>Copyright Institute for Scripture Research 1993-2021</head>
</figure>
</entryFree>

What do I do wrong please?
![image](https://user-images.githubusercontent.com/25449560/124426403-4a6f1d80-dd6a-11eb-9783-6019c8048cf9.png)

**Comment by refdoc** [comment]
We do not work or supply assistance to the Institute of Scripture Research which is none of that. Sent from my Huawei Mobile-------- Original Message --------Subject: [crosswire/xiphos] Display Image in TEI module (#1086)From: JohanMa To: crosswire/xiphos CC: Subscribed 
I want to display images in a TEI dictionary module, but receive an error message "An image's file size could not be determined. Xiphos cannot resize images to fit window.
The TEI text is:


 
 The Red Sea Crossing
Exo 14, Num 33
Copyright Institute for Scripture Research 1993-2021


What do I do wrong please?


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/crosswire/xiphos/issues/1086",
"url": "https://github.com/crosswire/xiphos/issues/1086",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
