### ISSUE TITLE
Study Pad not launching in Xiphos v4.2.1

### ISSUE THREAD

**Issue by GWM69** [crosswire/xiphos#1113]
Study Pad does not open on Linux Mint 20.03 when selecting Study Pad from the FILE menu.  Also unable to open the Journal editor.

**Comment by greg-hellings** [comment]
I'm assuming Mint still pulls packages from the Ubuntu repositories. In that case, you will need to either
1) Talk to the Ubuntu people about packaging the necessary dependencies; or
2) Work with Xiphos to update the editor code to a modern format.

Ubuntu has, for a long time, applied a Xiphos patch that removes the editor functionality but does not remove the options and buttons for it. They simply do not do anything in their builds. This is because Xiphos depends on antiquated versions of the HTML widget libraries for the editing code.

**Comment by LAfricain** [comment]
It's always the same issue #794 Very sad nobody take care of this.
