### ISSUE TITLE
Any latest version available ?

### ISSUE THREAD

**Issue by mangoose20026** [crosswire/xiphos#1164]
Any latest version available ?

**Comment by LAfricain** [comment]
Not yet...But I'm in favor of a new version without delay because the problem with nvidia cards is serious on the new version of debian/ubuntu.

**Comment by mangoose20026** [comment]
How about windows version ?

**Comment by LAfricain** [comment]
> how about windows version?

No idea I use only Ubuntu

**Comment by mangoose20026** [comment]
Is it possible to bundle for Windows?

**Comment by karlkleinpaste** [comment]
Just FYI.
Effort is being made toward a release. Much help is being offered by Scott Buchanan (@Phyrik) in the github auto-build processes. I have hopes that we will be able to do a release within a fairly short time.
Closing this for now, but watch for updates, and I will try to remember to comment here once more, after release.

**Comment by LAfricain** [comment]
@karlkleinpaste I'm really excited about it! Please give me a little advance notice so I can work on the French translation. I also recall the problem of reading strong's numbers in Hebrew modules, which was discussed on the list. Given that the solution had been found, would it be possible for the next version of xiphos to read it correctly?

**Comment by karlkleinpaste** [comment]
General announcement, which I will echo into the xiphos-devel mailing list:

4.3.0 release is planned for not later than end of March. If you have any last minute efforts to make, specifically translation updates, please schedule some time in the near future.

A lot has gotten done since the beginning of February (and more generally through the latter half of 2024), including updates to workflow integration, fixes to Windows build, fixes to detached parallel display and its context menu, improvements in tab behavior (re-ordering), locale handling, italic headings as a module option, font handling fixes, highlight fixes, multi-column and edge justification support, moving ~/.xiphos to ~/.config/xiphos per desktop standards, and RHEL9 compatibility (or, more generally, handling older systems with older libsoup and webgit2gtk).

@LAfricain I need a reminder, it's been too long: Solution to Strong's Hebrews? Drop email privately if you wish.

**Comment by LAfricain** [comment]
@karlkleinpaste I send you a part of the email thread. https://crosswire.org/pipermail/sword-devel/2024-April/050043.html
