### ISSUE TITLE
Add support and Add Tamil bible and Tamil bible related modules

### ISSUE THREAD

**Issue by mangoose20026** [crosswire/xiphos#1167]
Hi,

Please Add support and Add Tamil bible and Tamil bible related modules

Thanks

**Comment by karlkleinpaste** [comment]
A search through all the modules I can find available anywhere -- I keep an archive backup of known repositories -- shows no Tamil modules of any kind. But we in Xiphos don't have control over module creation, and the Xiphos module repo is named that only because almost all the modules it provides were created by people more or less closely associated with Xiphos itself. You'll have to ask for Tamil modules at [the Sword Project bug reporter](https://tracker.crosswire.org/secure/Dashboard.jspa).

If you wish to contribute a translation of the Xiphos interface to Tamil, please see Xiphos' menubar `Help`→`About Translation`.

**Comment by mangoose20026** [comment]
Links for your kind reference which you have searched but couldn't get it

http://www.biblesupport.com/e-sword-downloads/file/11047-tamil-romanised-bible/

http://www.biblesupport.com/e-sword-downloads/file/9589-tamil-bible/

https://wordofgod.in/wog/2022/01/26/download-tamil-bible-database-and-software-modules-for-android-iphone-and-laptop/

https://github.com/godlytalias/Bible-Database/tree/master/Tamil

https://tamil-bible.el-elupath-elu.in/

https://www.tamil-bible.com/tabletype.php?Type=Eng

**Comment by karlkleinpaste** [comment]
Please forward those links in a request you file in the Sword Project bug tracker mentioned above, but also be aware that Sword Project apps have no relation to e-Sword. They are distinct, the module formats are different, and there is no conversion process in existence, official or not, because the producer of e-Sword has made it clear for many years that [he prefers a closed ecosystem for e-Sword](http://karl.kleinpaste.org/rick.meyers/).

The Sword Project is some years older and more mature than e-Sword, and comprises far more cross-platform apps and vastly more Bible resources than e-Sword.

**Comment by mangoose20026** [comment]
[e-sword tamil bible modules.zip](https://github.com/user-attachments/files/16568104/e-sword.tamil.bible.modules.zip)

E-sword tamil bible modules downloaded and attached for your kind reference

**Comment by karlkleinpaste** [comment]
You didn't read a thing I wrote, did you?

**Sword Project apps have no relation to e-Sword. They are distinct, the module formats are different, and there is no conversion process in existence, official or not**

There is no practical value for generating a Sword Project module from having content of any e-Sword module.
