### ISSUE TITLE
Xiphos Crash 3.2.2

### ISSUE THREAD

**Issue by xiphos-bug-inhaler** [crosswire/xiphos#523]
BUG! Xiphos is about to crash due to a "STRDUP" error
Please report this error to the Xiphos Team with:

../src/gnome2/main_menu.c:654 "sword://%s/%s"

This happens when I go to click the "Preview" box under view on the menu bar.  I've searched for the above location, but am missing something somewhere....need help   Thank you in advance

Reported by: andrew5859

Original Ticket: [gnomesword/bugs/524](https://sourceforge.net/p/gnomesword/bugs/524)

**Comment by chriswadams** [comment]
I'm getting the same issue (Xiphos 4.2.1.7 crashes with a similar error message), on openSuSe Leap 15.4:

[CODE]BUG! Xiphos is about to crash due to a "STRDUP" error.
Please report this error to the Xiphos team with:

/home/abuild/BUILD/xiphos-4.2.1.7/src/main/display.cc1067'<b>%s %s</b><br/>'[/CODE]

This happens immediately whenever I open Xiphos. Karl Kleinpaste wrote: "the specific bug mentioned here was actually fixed long ago and that fix is already present in 4.0.0. but testing for your report uncovered another bug, a sort of ancillary bug, which has now also been fixed, and will be part of our next release."

I've tried updating both SuSe and Xiphos, but the crashes still happen. Karl also mentioned that there are builds for Ubuntu and Fedora, but nothing specifically for SuSe. I could try changing my OS to one of those two, if that's my only option, but I'd like to know if there are other possibilities before going down that road. Any help would be appreciated.

Thanks!
-chriswadams
