### ISSUE TITLE
SOCKS5 Support in Module Manager

### ISSUE THREAD

**Issue by xiphos-bug-inhaler** [crosswire/xiphos#720]
As pointed out already in the module manager, downloading modules can be dangerous in countries where the bible is illegal. As such, we should support the option of SOCKS5 Proxies (e.g. TOR) with no DNS Leaks as a setting in the module manager's connection options. In that way people could download modules fairly safely and their connections would be encrypted to prevent eavesdropping. 

It would also help users who cannot access FTP, as some instituions have blocked FTP (Port 21), or heavily throttled it. 

Reported by: *anonymous

Original Ticket: [gnomesword/bugs/182](https://sourceforge.net/p/gnomesword/bugs/182)

**Comment by karlkleinpaste** [comment]
we have always taken the perspective that, especially in the linux universe and to some extent in any networked world, the networking support of the machine as a whole is what should control.  per-application support of tunnels and proxies is philosophically broken; if the machine's access to the outside is a problem, the machine's access as a whole should be tunneled or proxied.  note that other platforms like smartphones can offer vpn services but it takes over the network access entirely, not per-application.

**Comment by ldutra** [comment]
I do not get why this is closed, as Xiphos cannot even use the system’s proxy configuration.

**Comment by gabrielmoura** [comment]
Please, I ask you to pay special attention to this function.

**Comment by ldutra** [comment]
Why no explanation of this lacking function?

**Comment by greg-hellings** [comment]
@ldutra - there is an explanation. @karlkleinpaste gave an explanation above.

It is philosophically broken to ask every app to have configurations for proxies, tunnels, and other networking stack support structures as that. Therefore, it is not desirable to implement this in Xiphos.

Furthermore, Xiphos does not actually perform networking operations. Those are handed off to the libsword interface. Since that does not support proxying, neither will Xiphos. If you want to have this feature exposed in Xiphos you would need to ask Sword for that support. It would not be hard to implement, as Sword can be configured to use libcurl, which definitely has SOCKS and other types of tunneling support.

This application is not the appropriate place for this to be implemented. If Sword chooses in the future to offer an interface for it, I'm sure Karl would not object to exposing the options in Xiphos.

**Comment by ldutra** [comment]
So, after so many years we learn this bug must be filed against libword.  Makes sense.  Thanks.
