### ISSUE TITLE
Add togglable Read/Unread Flags

### ISSUE THREAD

**Issue by xiphos-bug-inhaler** [crosswire/xiphos#725]
I want to read the entire bible in a year, but often I feel compelled to read it out of order, but when I do that I want it to count toward my goal of reading the entire bible. The problem, is how can I record what I read easily?

Ideally, before I engage in a reading plan, I'd like to be able to set the entire bible (or perhaps selected chapters) to unread, then as I read them, set them as read.

Ideally there should be an option to mark a chapter as read by checking a box when you get to the bottom of the chapter, which will mark it as read and load the next chapter ready to start reading at the top.

You should also be able to view an over-view of your read/unread status in such a way that makes it easy to adjust the status of each chapter, in the event that you read from a paper Bible while away from your computer.

Reported by: snowweb7

Original Ticket: [gnomesword/bugs/188](https://sourceforge.net/p/gnomesword/bugs/188)

**Comment by karlkleinpaste** [comment]
i feel that adding this as described would make for a particularly clunky interface, adding tracking widgets that are very special-case and don't fit in well with the rest of the interface. but i'm not sure what would be better. i can't consider any kind of auto-set for "have been read" because sometimes you open xiphos for methodical reading-through, and sometimes you open it just for random study that's not within such a plan.
for now, what i've implemented is a new journal template that offers the whole bible in books/chapters. you can edit the journal to mark what you've read, which provides that you can also add per-chapter notes as you go if you need.
it may not be the complete solution sought, but it will have to do for now.
