### ISSUE TITLE
Crash During Attempt to Install Modules

### ISSUE THREAD

**Issue by Gene-W** [crosswire/xiphos#759]
Hello,
I'm new to the program and recently encountered this problem. When I click Edit > Module Manager > Modules > Install/Update the program crashes.

I don't get an error or anything, but all of Xiphos shuts down.

Please let me know if I can provide any more information or reports. I'm running Linux Mint 17.3 and Xiphos 3.1.5-webkit.

**Comment by cjbayliss** [comment]
Thank you for reporting this bug!

The problem is due to Xiphos 3.1.5 not working with more up to date versions of GTK+ and WebKit, etc. The easiest solution is to install an up to date version of Xiphos.

I'd recommend this PPA by Unit193: https://launchpad.net/~unit193/+archive/ubuntu/crosswire

Basically, do this in a terminal:

~~~
sudo add-apt-repository ppa:unit193/crosswire
sudo apt-get update
sudo apt-get install xiphos
~~~

That should get you the latest version of Xiphos, and solve you problem. :)

(NOTE: you may need to run `sudo apt-get upgrade`)

**Comment by Gene-W** [comment]
Worked perfectly, thank you!!
