### ISSUE TITLE
Rewrite GTK3 port.

### ISSUE THREAD

**Issue by ghost** [crosswire/xiphos#761]
The GTK3 port is messy, and that makes it hard to maintain for new GTK3 releases. This should not be done until after moving to CMake. See issue #758

**Comment by cjbayliss** [comment]
This would make solving bugs like #756 a little simpler.

**Comment by karlkleinpaste** [comment]
no explanation for "messy" was ever offered. there is a certain amount of (unavoidable?) #ifdef usage, a good bit of which is usefully hidden under some macros in places like utilities.h (e.g. the UI_* macros, simplifying gtk2 -vs- gtk3 matters). since i'm not sure what is intended by "rewrite it" (rewrite what, exactly? rewrite it how?), i'm simply closing this on the idea that cleanliness is something that can be accomplished naturally over time.
