### ISSUE TITLE
4.0.4 win 32 crash on install or remove of breton/brezhoneg/br_en

### ISSUE THREAD

**Issue by jmichae3** [crosswire/xiphos#771]
crashdump has this info in the eventvwr.exe's application log:
Faulting application xiphos.exe, version 0.0.0.0, faulting module ntdll.dll, version 5.1.2600.6055, fault address 0x00010a19.

For more information, see Help and Support Center at http://go.microsoft.com/fwlink/events.asp.
Faulting application xiphos.exe, version 0.0.0.0, faulting module libsword.dll, version 0.0.0.0, fault address 0x00020532.

For more information, see Help and Support Center at http://go.microsoft.com/fwlink/events.asp.

this also may apply:
The description for Event ID ( 0 ) in Source ( gusvc ) cannot be found. The local computer may not have the necessary registry information or message DLL files to display messages from a remote computer. You may be able to use the /AUXSOURCE= flag to retrieve this description; see Help and Support for details. The following information is part of the event: Service stopped.

I also saw this about 3 or 4 times during the run, which tells me you are not properly detecting the windows disk media type:
"Application popup: ftp.crosswire.org: InstallManager.exe - No Disk : There is no disk in the drive. Please insert a disk into drive E:. 

For more information, see Help and Support Center at http://go.microsoft.com/fwlink/events.asp."

that was looking for the cdrom. usually you see the message "Windows - No Disk" and it's because there's a removable drive like a memory card with no card in it and using programming you think would work windows just goes nuts throwing error messages. it should only ask once and then if it gets a cancel, quit asking and take it as a no thank you.

I have code for this which I could donate if needed in c++ without copyright or license which is part of my df program if you want it, or give you the calls, but basically it starts by GetLogicalDrive() to get a bitmap list of windows drive letters that are active, then there's a call to get the default drive (letter), but you can ask if a disc is in using one of 2 DeviceIoControl() calls which is documented at Microsoft Developer Network (MSDN.Microsoft.com) here
https://msdn.microsoft.com/en-us/library/windows/desktop/aa363216(v=vs.85).aspx
and here
https://msdn.microsoft.com/en-us/library/windows/desktop/aa363404(v=vs.85).aspx
their use policy has been made public:
https://www.microsoft.com/en-us/legal/intellectualproperty/permissions/default.aspx
used with permission from Microsoft

I would have to look at my df code (might be on softonic.com somewhere) which is on my other box which is not up yet. my code has a large if+switch tree of detecting media types like cdroms and such. but the IOCTL_STORAGE_CHECK_VERIFY should work for you for cdrom stuff. looks like you already did some cdrom device scanning, so so far so good. at this point you could do this neat thing:

```
HANDLE hDevice=CreateFile("\\\\.\\E:", FILE_SHARE_READ,GENERIC_READ,OPEN_EXISTING,...);//open Joe's cdrom device
BOOL worked=DeviceIoControl(...,IOCTL_STORAGE_CHECK_VERIFY,...);
if (worked) {
    read cdrom;
} else {
    WaitForSingleObject(hDevice,30*1000); //would this work in place of while(sleep)?
    //while (!(worked=DeviceIoControl(...,IOCTL_STORAGE_CHECK_VERIFY,...))) {
    //    Sleep(1000*10);
    //}
}
//when done, CloseHandle(hDevice); before that you can use CopyFile(), etc.
```

see CopyFile2() at MSDN.microsoft.com https://msdn.microsoft.com/en-us/library/windows/desktop/hh449404(v=vs.85).aspx

IOCTL_STORAGE_CHECK_VERIFY might require a root directory ending of \ (\\) on the end of that path. some functions

**Comment by karlkleinpaste** [comment]
the only part of this that is xiphos-specific is the portion regarding xiphos failing due to libsword.dll. xiphos is packaged with our build of the sword lib, so that's a problem for us, but there's not enough information to say anything about it.  the lib faulted somehow...and that's it.  we need the semantic equivalent of a core dump, not just "hey, this thing died."

all the rest is ... nothing for us to handle.  the first line about xiphos failure complains of ntdll.dll, which is windows' own problem -- the fact that a failure can be induced in ntdll.dll is a bit heinous. the stuff about "not enough information to display info from a remote computer" has nothing to do with xiphos because xiphos doesn't deal with remote systems in such a manner.  anything to do with InstallManager.exe and media is related to the original sword app, aka The Sword Project For WIndows aka BibleCS, because xiphos' module manager doesn't work that way.

honestly, there is nothing in here for us to get a handle on.  mostly, it's just not related to xiphos at all, or what little info is provided gives nothing to work with.
