### ISSUE TITLE
Xiphos: unknown parallel module: AKJV

### ISSUE THREAD

**Issue by jmichae3** [crosswire/xiphos#774]
this dialog box pops up and piles up with every op. 4.0.4 win 32.

**Comment by jmichae3** [comment]
it also found its way in halfway from a list maybe I made in sword.

**Comment by karlkleinpaste** [comment]
"unknown parallel module" is because you have a module listed in your set of preferred parallel modules which is no longer present on your system -- you deleted it but the reference persists.  go to preferences, modules -> parallel, and delete the now-missing module. (yes, xiphos could delete such entries. the warning is needed anyway, because users import old settings from previous computers onto new machines where they have not loaded up the same set of modules.)

nothing to do with any *.iso complaint has a thing to do with xiphos' operation.
