### ISSUE TITLE
KJV defect the BRANCH should be THE BRANCH

### ISSUE THREAD

**Issue by jmichae3** [crosswire/xiphos#775]
this used to be in the TCR Bible. Zech 3:8, 12. at least one of them used to be THE BRANCH. what happened? translation error I suspect.

**Comment by DavidHaslam** [comment]
If this really is a module bug, then please use the modules tracker to report it instead of the Xiphos tracker!

But be sure to check it against the reference edition of the KJV first, not just any edition you happen to own. 

The CrossWire module aims to accurately reproduce the text of the 1769 Oxford Blayney edition. 

Karl will close this I expect. 

Best regards

David H

**Comment by jmichae3** [comment]
oops. search said 6:12, not 3:12. but OK, will check the module checker.

**Comment by karlkleinpaste** [comment]
xiphos' responsibility is to obtain text from the engine and display it. faulty content needs to be addressed by module maintainers.  see bug tracker.

https://www.crosswire.org/tracker/secure/Dashboard.jspa
