### ISSUE TITLE
Quotation Marks not Exporting

### ISSUE THREAD

**Issue by A3M0N** [crosswire/xiphos#778]
Xiphos 4.04, Xubuntu 16.04

When I export scriptures from the ESV (from the Crosswire repository), the quotations marks aren't being exported with the rest of the text. 

Also, with "Reference Last" selected, the trailing parentheses isn't included.

**Comment by karlkleinpaste** [comment]
very odd.  plain old " seems ok.  unicode “” fail.

**Comment by karlkleinpaste** [comment]
It's a sword engine bug, that is, the underlying library that provides access to texts.  Marks are not lost in HTML output, they are lost in plain text output.  The difference is in underlying use of engine's stripText() in our code, induced by ESV's use of OSIS' <q> for quotation -- the strip happens before the quotation marks are encoded.  Not something that can be fixed in Xiphos itself.  Bug has been added to Sword bug tracker for cogitation there.

Also, the 2nd part about missing paren is wrong.  I just tested, both plain and HTML, and checked code.  Closing paren is present.

**Comment by karlkleinpaste** [comment]
Addendum: GitHub bug, can't type angle-bracketed doodads in comments.

Should be: ...ESV's use of OSIS' "[q]" for quotation, except substitute angle brackets for square brackets to get what I mean...

Gosh this is a dumb GH bug.  Bugs in the bug tracker, gotta love it.  How many programmers doing UI work want to report on bugs using angle brackets?  Sheesh.

**Comment by A3M0N** [comment]
Can you link to the bug report for this in the Sword project? 

I still get the missing closing paren. It's not every time, I'm not sure what circumstances it happens. I'll try to remember next time it happens to note it and the scripture I was exporting. I just add the paren on the end, it's not a huge deal really.

**Comment by karlkleinpaste** [comment]
http://www.crosswire.org/tracker/browse/API-191

The fix for this has been done, I think, but we've been a long time waiting for an updated Sword engine release.

**Comment by A3M0N** [comment]
So we're just waiting on a Sword engine update, then a Xiphos update?

Richie Anderson
Family Life and Youth Minister
Westside Church of Christ - Alvin, TX
Office: 281-388-2252
Mobile: 850-586-1694
http://alvinwestsidechurch.com/

**Comment by karlkleinpaste** [comment]
doesn't even need a xiphos update. the engine update will take care of the matter entirely, beneath the awareness of xiphos. xiphos' behavior here is simply to request content from the engine and paste that content into the window. xiphos is (nearly) blind to the form that content takes.

the question is whether the engine update will be a minor "point" release or something more serious, changing the version stamp in a manner to require a rebuild/re-release of xiphos. either way, xiphos itself needs no change.
