### ISSUE TITLE
Xiphos preview pane doesn't display Gurmukhi script after a search for some Punjabi text 

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#780]
Details.

**xiphos.exe 4.0.4 (gtk2 webkit1)** on Windows 7 x64 Home Premium edition.

Module (just made for a project I'm helping).

Punjabi Bible - the Unicode text uses the Gurmukhi script.

Main Bible pane displays OK with either default **Sans** font or changed to **Code2000** font.

After a search for **any Punjabi word**, the preview pane displays verse text incorrectly. 
e.g. See screenshot.

![screenshot 2017-01-10 21 26 57](https://cloud.githubusercontent.com/assets/16325414/21825425/9471a6b8-d77b-11e6-8f34-5f7520798211.png)

NB. The module **search index** had already been made before I encountered this issue.

_I can readily send you the module by email privately for test purposes._

**Comment by DavidHaslam** [comment]
**Further evidence:**

The bad preview pane display occurs only after the search contains _Gurmukhi_ text.
A search for _alphanumeric_ text does not lead to the same problem.

e.g. The text (still being proofread) contains a _spurious_ number 1 in some verses.
Module search for 1 gave 7 verses as matches, and the preview for each of them was OK.

**Comment by DavidHaslam** [comment]
btw. I changed the module font to **Raavi Normal** (which also supports Gurmukhi).
_This made no difference to this issue._

**Comment by DavidHaslam** [comment]
**Further information:**

This issue occurred for a module in which the Punjabi source text was **not** normalized to NFC during module build.

If the module is rebuilt with the Unicode normalized to NFC, the search results were displayed correctly.

**Comment by DavidHaslam** [comment]
However, Xiphos does **not** automatically normalize a (Punjabi) search string when it is entered.

Users accustomed to writing the Gurmukhi letters **LLA SHA KHHA GHHA ZA FA** instead of the letters **LA SA KHA GA JA PHA** with a **NUKTA** sign will thus experience difficulties with the search feature.

**Comment by karlkleinpaste** [comment]
xiphos doesn't normalize anything.  xiphos shuts off greek accents and hebrew & arabic vowel points prior to any search so that such things can't ruin an otherwise-useful search.

i don't want to get Yet Another Online Account (i.e. your Box offer), so i picked on HinERV as my test victim for the moment. i tested in both linux and windows builds of 4.0.6a. i did sidebar search both with and without lucene index.  xiphos displays results fine either way: i tested by pasting the apparent word for "light" in gen.1.3 into search; it returned a verse list including gen.1.3, and that verse in previewer appears normally, including highlight.

i can only surmise that there's something deeply funky about font handling of punjabi itself, or that the engine has a problem with it, because what xiphos is doing is correct in all cases, both seen externally (black box, good display) and internally (white box, code examination).
![hindi](https://user-images.githubusercontent.com/7548920/30000183-75d726e2-9030-11e7-93ab-de577a0ca533.gif)

closing for now; if more information can be provided, i'll look again, but at this time i can't even imagine what peculiar font-specific sensitivity is involved that would cause such a problem.
