### ISSUE TITLE
A search for the regexp [\x{0A3E}-\x{0A4C}]{2,} caused Xiphos to crash

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#781]
Are some types of **regexp** not permitted?

This one cause Xiphos to crash.  `[\x{0A3E}-\x{0A4C}]{2,}`

i.e. End the application suddenly with the search progress bar at around 10%.

The expression specifies two or more consecutive instances of a **Gurmukhi** vowel sign.

cf. The pattern works OK in **Notepad++**.

**Comment by DavidHaslam** [comment]
I've invited you to a private folder in my Box account that contains two test build SWORD modules for the Punjabi 1945 Bible. 

The same regexp search in Panjabi for this pattern still crashes Xiphos 4.0.6a 32-bit (installed earlier today in my Win7 x64 PC).

**Comment by DavidHaslam** [comment]
It still crashed when I searched the module **PolUGdanska** (version 2.0) that was released last week.

I wonder whether the crash only happens in the Windows editions?

**Comment by DavidHaslam** [comment]
A search even for `\x{0A3E}` still crashed.

**Comment by karlkleinpaste** [comment]
yup, windows crash, no crash in fedora. the mechanism by which to reach into search is not os-sensitive, ergo there is something deeper in the windows aspects that is causing this, outside xiphos' control. i'm going to mark it closed because this is (as ghellings surmised in irc) probably an artifact of windows' failure to grasp utf-8 fully. we do what we can in xiphos to be utf-happy but at some point we run aground on the rocks of the platform.

**Comment by DavidHaslam** [comment]
Understood. I already knew that Windows leans heavily towards UTF-16.
