### ISSUE TITLE
Lucene search not as intelligent as on And Bible

### ISSUE THREAD

**Issue by teresaejunior** [crosswire/xiphos#782]
Hello! I have both Xiphos on my desktop and And Bible on my phone. On both, I have created a Lucene index. With And Bible, I can search for words and the results automatically include conjugation for the verbs. On Xiphos, I have not found a way to get similar results.

For example, the verb "cry" in my language is "chorar". If I search for "chorar" on And Bible, I get results for "chor**ou**" (he cried), "chora**stes**" (you cried). On Xiphos, I only get simple results containing the word "chorar".

**Comment by DavidHaslam** [comment]
Have you ever tried the Advanced Search feature in Xiphos?

Which version of Xiphos do you have?

Windows or Linux?

Which module was this?

**Comment by teresaejunior** [comment]
I have tried the Advanced Search, but the results are the same.

This is a problem I have noticed years ago on Xiphos 3.1.5 on Debian, but I still see it on Xiphos 4.0.4 on the latest Ubuntu.

The module is available on https://app.box.com/v/siriarah as *biblias/ACF2007/ACF2007-sword.zip*

**Comment by DavidHaslam** [comment]
Thanks for details.

Please edit the issue subject to remove the first word "**Lucene** ".
The same results occur in **Xiphos** either _with_ or _without_ the index.
(cf. The index merely makes searching much, much faster!)
You can readily test this by using
 **Edit | Module Manager | Maintenance** 
to select the module and remove the index.

According to 
https://crosswire.org/wiki/Choosing_a_SWORD_program#Search_and_Dictionary
**Fuzzy search** is supported by Xiphos but not by AndBible.

_But is it really this that you're after?_

Or are you looking for search based on the _common stem_ of these words in Portuguese?

We'd need to consult the **AndBible** developer to find out he _apparently_ "succeeds" where Xiphos "fails".

I could open the **ACF2007** module in **PocketSword** for comparison, but there's a general issue for search in **PS** since **iOS 9.x** was released, and it's now more or less a _showstopper_, even when a module is installed wirelessly as a Zip file also containing the search index generated by (say) Xiphos on a PC.  Unlike Xiphos, PS cannot perform a search _unless_ there is an index.

**Comment by DavidHaslam** [comment]
In Xiphos, the method to obtain what I think you are after is to use a [Regular Expression](https://en.wikipedia.org/wiki/Regular_expression) **search type**.

For example, taking all but the last two letters of your search word **chorar** - a search for the RegExp **chor\w+** will certainly find chor**ou** and chor**astes** among the 169 results, though the search key matches are **not** highlighted in this mode.

I think your dissatisfaction may be alleviated to some degree by learning how to use RegExp.

**Comment by greg-hellings** [comment]
Designating this as a "Lucene" issue is correct. However, designating it as
a Xiphos bug is likely not. AndBible is Java based and can use the
canonical Lucene analyzers. Xiphos is C/C++ based and has to rely on the
CLucene library. Lucene/CLucene provide a method of searching that allows
analysis of roots, as the OP observed in AndBible.

However, CLucene is woefully neglected in terms of its implementation and
maintenance as an upstream project. While the Lucene project is very well
maintained and very active, CLucene has been essentially abandoned for a
very long time. It does not receive nearly the number of updates to
non-critical (e.g. language specific analyzers like this feature would rely
on) code that Lucene does. Compare CLucene's last commit was in 2013 and
last release was in 2011 whereas Lucene's last release was 8 Nov 2016 and
its last commit was 6 hours ago.

CLucene, however, is an artifact of the engine and not of Xiphos.
Therefore, if this bug is to be filed anywhere, it should be filed with the
SWORD engine and not with Xiphos.

**Comment by DavidHaslam** [comment]
Thanks for chipping in, Greg. :)

teresaejunior ....
To report issues for the SWORD API, please visit http://www.crosswire.org/tracker/issues/
and choose SWORD as the **Project** when you create it.

**Comment by teresaejunior** [comment]
Thanks for all your help! I will open an issue there!

**Comment by DavidHaslam** [comment]
One good thing came of it. We learned about the ACF2007 module.

**Comment by teresaejunior** [comment]
Yes, it is the closest to the KJV you can find in the Portuguese language, and follows the Textus Receptus only.

You can find more information about the module on https://siriarah.wordpress.com/2010/10/31/biblia-almeida-corrigida-fiel-2007-acf-2007/

**Comment by dmsmith** [comment]
AndBible (JSword) does a stemmed search by default on non-English languages if it can. SWORD lib does not. 

Cent from my fone so theer mite be tipos. ;)

**Comment by dmsmith** [comment]
Fuzzy search is supported by all JSword front ends including AndBible. 

Cent from my fone so theer mite be tipos. ;)

**Comment by dmsmith** [comment]
In lucene chor* will do a wildcard search. 

Cent from my fone so theer mite be tipos. ;)

**Comment by teresaejunior** [comment]
Wildcards and regexes do work, but it would be better to have such feature because most users don't know how to use them, and also because of small verbs like the English verb **go**, where not only it will find a lot of unrelated stuff, but it can be conjugated as **went**!

**Comment by DavidHaslam** [comment]
Aside: How does JSword search cope with Bible translations in which the writing system does not have a space between words?

**Comment by greg-hellings** [comment]
You would need to check with the JSword repository. I imagine it feeds the
language code into the documents as it creates them, and Lucene selects the
parser, lexer, etc based on that if it has one. That's another area where
CLucene is behind and will continue to fall farther behind as it is not in
active development.

**Comment by dmsmith** [comment]
That's what JSword does. 

Cent from my fone so theer mite be tipos. ;)
