### ISSUE TITLE
Xiphos does not hide some headings in the ESV module

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#785]
### Example illustrated:

The second **title** element doesn't hide in Xiphos.

&lt;title>The Bride Confesses Her Love&lt;/title>

$$$Song of Solomon 1:2
&lt;title subType="x-preverse" type="section">She&lt;note n="1" osisID="Song.1.2!note.1" osisRef="Song.1.2" type="translation">The translators have added speaker identifications based on the gender and number of the Hebrew words&lt;/note>&lt;/title>**&lt;title>The Bride Confesses Her Love&lt;/title>**&lt;l sID="x10893"/>Let him kiss me with the kisses of his mouth!&lt;l eID="x10893" type="x-br"/>&lt;l sID="x10894"/>For your &lt;note n="b" osisID="Song.1.2!crossReference.b" osisRef="Song.1.2" type="crossReference">&lt;reference osisRef="Song.4.10">ch. 4:10&lt;/reference>&lt;/note>love is better than wine;&lt;l eID="x10894" type="x-br"/>

Similar places in Song behave the same way.

**Comment by DavidHaslam** [comment]
Screenshot with **Hide headings** and (Hide verse numbers),

![screenshot 2017-02-06 17 16 51](https://cloud.githubusercontent.com/assets/16325414/22660680/5fd52518-ec9a-11e6-917d-56f92a4f7f54.png)

**Comment by DavidHaslam** [comment]
The same erratic behaviour does not occur with **PocketSword**.

**Comment by DavidHaslam** [comment]
A simple workaround might be to move the first &lt;/title> so that one title encloses the other.

    &lt;title subType="x-preverse" type="section">She&lt;title>The Bride Confesses Her Love&lt;/title>&lt;/title>

I'm pretty sure that would work, but we shouldn't have to tweak the module just because one front-end apparently misbehaves.

**Comment by DavidHaslam** [comment]
Also reported to CrossWire tracker as [MOD-326](http://www.crosswire.org/tracker/browse/MOD-326)

**Comment by karlkleinpaste** [comment]
yup, it's wrong. tell it to the engine. xiphos processes whatever the engine hands it. if pocketsword doesn't have this problem, then it has an older or newer or modified engine that doesn't have this error. xiphos en/disables headers in one fashion; once en/disabled, xiphos processes everything the same, including looking for headers, whether they're supposed to be there or not. if xiphos finds them, it's because the engine provided them, even if the engine shouldn't have.
