### ISSUE TITLE
Xiphos didn't find festival to start TTS

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#786]
### xiphos.exe 4.0.4 (gtk2 webkit1)
Windows 7 x64 Home Premium Edition

Tried read aloud with ESV module open at Song 1.

After some egg timing I got this popup:

![screenshot 2017-02-06 18 39 13](https://cloud.githubusercontent.com/assets/16325414/22661098/fe53b000-ec9b-11e6-8763-be9ebe8a32dd.png)

Yet Xiphos does have **festival.exe** in the right place.
`C:\Program Files (x86)\CrossWire\Xiphos\festival`

**Comment by DavidHaslam** [comment]
When I tried it again, the TTS worked as expected. So it must be an initialisation bug.

**Comment by karlkleinpaste** [comment]
the initialization "bug" is that it takes windows a geological epoch to start festival. the code is written to allow a fixed 2sec for the subprocess to start. apparently that's not enough in many versions of windows, though it has never been a problem in any instance of linux i've seen nor in my own windows systems.  i'm not inclined to lengthen the time for windows' sake because frankly it's ridiculous that it takes >2sec to do something so trivial; in most instances it's enough.
