### ISSUE TITLE
Reduce minimum size

### ISSUE THREAD

**Issue by singpolyma** [crosswire/xiphos#812]
https://github.com/crosswire/xiphos/blob/e6057851ed4489d81721e8ee8fa923687f484851/src/gnome2/main_window.c#L937 limits the smallest size the window can be to 680x425 which means xiphos cannot be used as an option on small-screen devices (such as the pocketCHIP whose resolution is 480x272).

I have tested building a version with that line commented out, and it allows the window to be sized much smaller, while still being usable.

**Comment by karlkleinpaste** [comment]
i have to say that i ... hesitate ... to make this change, reason being that xiphos is a heavyweight, full-featured kind of app, in every sense, genuinely never intended to be used on miniature devices; the size was knocked down to 680x425 about 8(?) years ago on request simply because there were laptops with PAL-standard screens (768x576) and after allowing for panels etc, that would fit.

to bring this down even further to such a tiny device is at the border of absurd to me. i looked up the pocketCHIP -- have you actually built xiphos for this device and used it there? xiphos is really mouse-dependent, and relies particularly on right-click for context menus in a number of places. does this device even offer an equivalent for a mouse-centric interface?

on the one hand, yeah, sure, i could edit the file and change the numbers. perhaps instead i could use gtk_widget_set_default_size, which would preserve the current initial habit, but allow for the freaks among you (c'mon, be honest) to shrink it anyway.

**Comment by singpolyma** [comment]
Yes, I have built xiphos on my pocketchip with the line in question commented out and it works well and I use it now there :)

The device simulates "right click" events when I tap the touch screen while holding the ctrl key.

The "default size" option that you suggest might be a good compromise.

**Comment by karlkleinpaste** [comment]
i made this change. i'm not very happy about it, but i made it. i downsized xiphos to 480x272, and if you think that's usable, goodie for you but frankly i'm convinced you're nuts.  your call.  4.0.6 will be released soon.
