### ISSUE TITLE
Preview pane does not render words marked using the divineName element as small-caps

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#813]
If a verse displayed in the preview pane contains the **divineName** element, the marked word is displayed as normal text rather than being rendered with small-caps.

In the screenshot from a Polish Bible module being developed, the word **Pana** in II Kings 14:25 is thus marked. (FIO: The example xref was from II Kings 13:12.)

![screenshot 2017-08-01 15 30 31](https://user-images.githubusercontent.com/16325414/28830405-83a3d606-76ce-11e7-9279-f1d6b41c51fd.png)

The main text displays this word correctly as small-caps. The preview pane incorrectly as normal text.

**Comment by greg-hellings** [comment]
I thought that the Preview Pane was designed to strip out all internal
formatting of the text and leave only the plain text.

**Comment by DavidHaslam** [comment]
If that's the case and is documented, then fine. I'd not read that anywhere before.
But yes - words marked with **transChange** are not rendered as italics in the preview pane either.
Interesting though that previewed text still has all its own xref tags.

FWIW. PocketSword displays divineName text in the footnote pane in all uppercase (reported).
Yet it doesn't render added words with italics either.

**Comment by karlkleinpaste** [comment]
as usual, xiphos displays by just asking the engine for renderText() and pasting the result, using whatever formatting options are in force at the time. if it's not italic, it's because the engine decided it shouldn't be. not a xiphos probelm, as far as i can tell.

i do see the issue. i experimented a bit, found NASB Num 14.27 xref Num 11.1 where "some" and "it" should be italicized but are not. not under my control.
