### ISSUE TITLE
Use Mallard to rewrite user documentation

### ISSUE THREAD

**Issue by yetist** [crosswire/xiphos#815]
[Mallard](http://projectmallard.org/index.html) is a markup language to provide user help documents, and [yelp supported](https://wiki.gnome.org/Apps/Yelp/Mallard) it. 
Does Xiphos plan to use it?

**Comment by karlkleinpaste** [comment]
considering that i never heard of it, no.
if there's value in it, it could be considered. no promises.

**Comment by refdoc** [comment]
Matthew Talbert mentioned Mallard some 10 years ago as the coming new Gnome standard. Apparently less hierarchical and more suitable to How to , topical documentation than DocBook XML Not sure what has come from that.I certainly do not see it as a priority for anything I want to achieve. PeterSent from my Huawei Mobile-------- Original Message --------Subject: Re: [crosswire/xiphos] Use Mallard to rewrite user documentation (#815)From: karl kleinpaste To: crosswire/xiphos CC: Subscribed considering that i never heard of it, no.
if there's value in it, it could be considered. no promises.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@karlkleinpaste in #815: considering that i never heard of it, no.\r\nif there's value in it, it could be considered. no promises."}],"action":{"name":"View Issue","url":"https://github.com/crosswire/xiphos/issues/815#issuecomment-321725253"}}}

**Comment by yetist** [comment]
I started working for it, see [here](https://github.com/yetist/xiphos/tree/mallard)

**Comment by domcorbex** [comment]
Hi Yetist!

See my Gitlab repo: https://gitlab.com/domcox/xiphos-cmake/tree/master/
I've started to port Xiphos to CMake, building on Linux is ok, (tested on Debian+Fedora) but not on Windows actually.
I also completed the full port of Help to Mallard. See the mhelp directory.

**Comment by yetist** [comment]
OK, you did a good job.
I hope you can finish the test of Windows platform as soon as possible, and then merge the code together.

**Comment by karlkleinpaste** [comment]
handled via commit ec38ee8329ddbce061607c7adca83009a72eed58
huge thanx to dom
