### ISSUE TITLE
An unknown button

### ISSUE THREAD

**Issue by threelegcat2015** [crosswire/xiphos#828]
Here is an screenshot from the Find dialog for Xiphos 4.0.7 on Fedora 26 with an unlabelled button in the middle. Shouldn't it be supposed to have a string or an icon for it?
![2017-10-09 16-08-50](https://user-images.githubusercontent.com/13062920/31335762-8ad0cdec-ad26-11e7-9c40-ec39473aaf17.png)

**Comment by refdoc** [comment]
This is an untranslated menu label presumably. Are you willing to fix the Chinese translation for us? Look under the locales.d folder and go through the relevant file, fixing items as you go along.  Thank you!

**Comment by threelegcat2015** [comment]
I'm sorry that I'm not technical enough to know where it is. But does it seems to be a common bug for all locales?
![screenshot from 2017-11-06 16-27-41](https://user-images.githubusercontent.com/13062920/32431834-f334a8a0-c30f-11e7-9b9f-996a8028c244.png)

**Comment by refdoc** [comment]
Sorry, I managed to delete your comment, my since apologies. Anyway, if you could identify what the button should say, in Chinese I can take it from there. PeterSent from my Huawei Mobile-------- Original Message --------Subject: Re: [crosswire/xiphos] An unknown button (#828)From: threelegcat2015 To: crosswire/xiphos CC: Peter von Kaehne ,Comment I'm sorry that I'm not technical enough to know where it is. But does it seems to be a common bug for all locales?


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@threelegcat2015 in #828: I'm sorry that I'm not technical enough to know where it is. But does it seems to be a common bug for all locales?\r\n![screenshot from 2017-11-06 16-27-41](https://user-images.githubusercontent.com/13062920/32431834-f334a8a0-c30f-11e7-9b9f-996a8028c244.png)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/crosswire/xiphos/issues/828#issuecomment-342079045"}}}

**Comment by refdoc** [comment]
The problem lies somewhere in src/gnome2/find_dialog.c  around line 280

The code seems to be there, the Chinese translation exists, but somehow neither the icon nor the text make it to the display. I looked and do not understand what is missing. Over to someone else
