### ISSUE TITLE
Xiphos doesn't display footnotes in titles

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#840]
If I have a note in a titles, I can't read it, it will not display. First I thought i was an issue in the osis file, but andbible read it all perfectly.

**Comment by LAfricain** [comment]
Your example is not a good one, I speak about footnotes on non canonical titles. I will send you an example with konvb (Rm 2,1, but currently this module is not yet published), but It can be after 2 weeks...

**Comment by karlkleinpaste** [comment]
ok... i suspect you're going to come up against a limitation in the sword engine, with its sometimes subtle differences from jsword, which is what drives andbible. but we'll see what other example you have.

**Comment by LAfricain** [comment]
[This file](https://gitlab.com/lafricain79/konvb/edit/master/osis/konvb.osis.xml) can help you to see (Rom3:1). If you don't have time wait I'll come back to travelling.
```
<div type="section">
        <chapter sID="Rom.3" osisID="Rom.3" n="3"/>
        <title>Bayuda ti bamimpani, bo yonso me kota nsoki ; Nzambi ke gulusa bo yonso na mawa na yandi<note placement="foot">1-4, Polo ke yuvula : « Keti bayuda me luta ve bantu yankaka ? » Mvutu kele nde : Nzambi ke kwamina na ku­tonda bayina ya yandi solaka ntete. Mambu yai ta monika pwelele na chap. 9-11. Kana bayuda yankaka me buya na kukwikila, bankaka me kwikila kwa bo. Bo kele « Ndambu ya me bika » (fr. le petit reste) ya Iz 1, 9 kuzabisaka na ntwala. Na meso ya Polo, yo ke tadila bayuda ya me kituka bakristu. Ata bayuda yankaka me kwamina ve na kutula ntima na Nzambi, Nzambi ke fula na kumonisa Ndinga ti Masonga na yandi, Ngolo ti Lunungu na yandi. Awa Polo me yibukisa Nkb 50 (He 51, 6b) na kigrek (LXX). Ye mambu yai ke ko­tisa ngindu ya ta landa. 5-8, Polo ke songa ntete ngindu ya bayina ke sosa na kusambisa Nzambi. Bo nde : « Ka­na mawa ya Nzambi unkwa masonga ke monika pwe­lele ntangu muntu me bwa na masumu, Nzambi kele na ntima ya mbi ntangu yandi ke lola nsumuki ». Polo ke lo­mba na kukeba. Yandi ke bu­ya na bo kutuba nde : « Sa­mbu na ma­mbote ya dienga, bantu le­nda kuzinga na kati ya masumu ». Mpila ya kukatula ma­kasi ya Nzambi kele ve. Yo ke songidila nde : Yandi lenda ve kundima mambi na beto. Di­sumu ya muntu, yo kele ve ki­ma ya mbote, ata Nzambi le­nda kusonga mawa na yandi na nsumuki. Luswaswanu na ka­ti ya masumu ti nsumuki, yo kele mambu ya mfunu ya nene.</note></title>
        <p><verse sID="Rom.3.1" osisID="Rom.3.1" n="1"/>Na nki mambu Bayuda ke luta bantu yankaka ? Nki mfunu ya luyotisu ?<note placement="foot">1-4, Polo ke yuvula : « Keti bayuda me luta ve bantu yankaka ? » Mvutu kele nde : Nzambi ke kwamina na ku­tonda bayina ya yandi solaka ntete. Mambu yai ta monika pwelele na chap. 9-11. Kana bayuda yankaka me buya na kukwikila, bankaka me kwikila kwa bo. Bo kele « Ndambu ya me bika » (fr. le petit reste) ya Iz 1, 9 kuzabisaka na ntwala. Na meso ya Polo, yo ke tadila bayuda ya me kituka bakristu. Ata bayuda yankaka me kwamina ve na kutula ntima na Nzambi, Nzambi ke fula na kumonisa Ndinga ti Masonga na yandi, Ngolo ti Lunungu na yandi. Awa Polo me yibukisa Nkb 50 (He 51, 6b) na kigrek (LXX). Ye mambu yai ke ko­tisa ngindu ya ta landa. 5-8, Polo ke songa ntete ngindu ya bayina ke sosa na kusambisa Nzambi. Bo nde : « Ka­na mawa ya Nzambi unkwa masonga ke monika pwe­lele ntangu muntu me bwa na masumu, Nzambi kele na ntima ya mbi ntangu yandi ke lola nsumuki ». Polo ke lo­mba na kukeba. Yandi ke bu­ya na bo kutuba nde : « Sa­mbu na ma­mbote ya dienga, bantu le­nda kuzinga na kati ya masumu ». Mpila ya kukatula ma­kasi ya Nzambi kele ve. Yo ke songidila nde : Yandi lenda ve kundima mambi na beto. Di­sumu ya muntu, yo kele ve ki­ma ya mbote, ata Nzambi le­nda kusonga mawa na yandi na nsumuki. Luswaswanu na ka­ti ya masumu ti nsumuki, yo kele mambu ya mfunu ya nene.</note> <verse eID="Rom.3.1"/>
```

**Comment by karlkleinpaste** [comment]
gitlab insists that i sign in, and i just don't want to create Yet Another Website Account For Something I Don't Expect To Use.
when you can hand me a complete module to test, i'll look again. up to this point, i don't see why there would be anything to distinguish xref/note handling in any kind of [title], canonical or not.

**Comment by greg-hellings** [comment]
This link (view instead of edit) should be viewable without authentication:

https://gitlab.com/lafricain79/konvb/blob/master/osis/konvb.osis.xml

**Comment by LAfricain** [comment]
Yes you thé project is public

**Comment by karlkleinpaste** [comment]
do you have a ready-made .conf for this?

**Comment by LAfricain** [comment]
Hello,
With the new [adyeth](https://github.com/adyeths/u2o) script orefs.py, it is now displaying, but the note is at the beginning of the next line. See the screenshot.
![note-xiphos](https://user-images.githubusercontent.com/19690477/39208730-bb3a8d7c-47fb-11e8-8140-b089efba86aa.png)

**Comment by karlkleinpaste** [comment]
in order to generate this module so i can experiment, i need **your .conf** and **whatever options you gave to osis2mod**.
or do i need this adyeth(?) thing, **orefs**? give me the configuration and tools, and how to invoke them, to get to something i can test.
or just give me **an archive file containing the fully-generated module**.
ultimately, i suspect this is going to come down to "the sword engine generated incorrect xhtml" but i need a full, concrete example with which to work in order to get there.

**Comment by LAfricain** [comment]
You'll find the complete module [here](https://gitlab.com/lafricain79/konvb/tree/master). I added the sword folder.

**Comment by karlkleinpaste** [comment]
as i surmised from the beginning, it's a sword error.

interpolating angle brackets to square to get past github's stupid editor, the title is rendered by sword as:

[h3 class="title"]Malongi ya Polo ke kwelana ti Mikanda ya santu ; Bayuda ti bamimpani, bo yonso me kota nsoki[a class="" href="passagestudy.jsp?action=showNote&type=n&value=&module=KonVb&passage=Romans+3%3A9"][small][sup class="n"]*n1[/sup][/small][/a][/h3]

what's relevant here is in the middle of the "passagestudy" arguments, namely the "value" element. "value" erroneously has no, uh, value. in the normal case, that should be a number, a reference to the internally-labeled element within sword's syntactic breakdown of the verse to its components including text, footnotes, xrefs.

example of a correct reference from verse 1, after "luyotisu":

[a class="" href="passagestudy.jsp?action=showNote&type=n&value=1&module=KonVb&passage=Romans+3%3A1"][small][sup class="n"]*n1[/sup][/small][/a]

note "value=1" because it's the first (and only) non-verse-text element within the verse. this is why the title note is not reachable, because when xiphos extracts those arguments from the passagestudy url, it finds an empty value= and cannot use that to ask sword for the right component. somehow, in this case (but not others), the note being within verse heading content has confused the engine into neglecting to include a value.

not a xiphos error. you'll have to report it as a bug to sword.

**Comment by DavidHaslam** [comment]
SWORD bugs should be reported [here](http://tracker.crosswire.org/projects/API/).

**Comment by LAfricain** [comment]
Can you do it please, I have no account yet?

Le 28/04/2018 à 13:37, David Frank Haslam a écrit :

**Comment by DavidHaslam** [comment]
It's preferable that you register for an account and then add the issue.

I don't fully understand the underlying technical details.
I'm not one of the code developers.

**Comment by karlkleinpaste** [comment]
http://tracker.crosswire.org/projects/API/issues/API-208

**Comment by LAfricain** [comment]
Thank you Karl!

Le 28/04/2018 à 16:38, karl kleinpaste a écrit :
