### ISSUE TITLE
Multiple GTK deprecation warnings

### ISSUE THREAD

**Issue by refdoc** [crosswire/xiphos#841]
Since GTK 3.22 there are are multiple deprecation warnings around Menu coding

**Comment by karlkleinpaste** [comment]
one remaining menu warning in treekey-editor.c was updated.
slib-editor.c warnings are not being addressed, since it needs to go away when the editor issues are resolved.
the only other warnings are for xiphos.c gdk_screen_get_height/width, and i don't grasp how i'm supposed to put poorly documented "per monitor" functions to use for this yet.

**Comment by refdoc** [comment]
That last one was also my problem - I have spent several days trailing non-existent documentation.
