### ISSUE TITLE
Detached sidebar empty

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#858]
If I detach the sidebar to the windows, it is empty, and it is impossible to resize it. See the screenshot.

![sidebar](https://user-images.githubusercontent.com/19690477/34956844-39558b9a-fa2b-11e7-9856-27a6336fe626.png)

**Comment by karlkleinpaste** [comment]
once in a blue moon, someone actually tries to use detached sidebar, something heinous is found in the process, and a bug reports gets written. but i have not ever seen any particularly serious use of xiphos' detached sidebar since it was first offered, somewhere around 2007 -- a decade-plus of presence through 3 different display toolkit environments with nearly no use.

because of the extremely limited use in practice of a dodgy feature that has never had serious use in the community, i am debating simply deleting the ability rather than to spend time working on code whose userbase may comprise literally 3 people.

if you can make a good case for this being valuable, i'll reconsider, but otherwise i intend to delete the capability from the menu soon.

**Comment by LAfricain** [comment]
For me it is not very useful. I made this bug report to be conscientious. If you remove the option it's not a  problem for me.
