### ISSUE TITLE
Please update your translation tools

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#862]
Hello,
During this week I translated 30% of the file into Italian on launchpad, when I noticed that the file was very old!! I think launchpad is a nice tool for translation, for me the best way. 
For this reason please synchronize launchpad with github or suppress the possibility to translate on it.

**Comment by refdoc** [comment]
I do not think that what is on Launchpad is under our control. Not sure who controls it, but probably a defunct packaging team. Sent from my Huawei Mobile-------- Original Message --------Subject: [crosswire/xiphos] Please update your translation tools (#862)From: LAfricain To: crosswire/xiphos CC: Subscribed Hello,
During this week I translated 30% of the file into Italian on launchpad, when I noticed that the file was very old!! I think launchpad is a nice tool for translation, for me the best way.
For this reason please synchronize launchpad with github or suppress the possibility to translate on it.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Please update your translation tools (#862)"}],"action":{"name":"View Issue","url":"https://github.com/crosswire/xiphos/issues/862"}}}

**Comment by LAfricain** [comment]
> Not sure who controls it

How can one know? There are many languages involved. How to take control on it?

**Comment by LAfricain** [comment]
@refdoc you seem to be in the xiphos team on [launchpad](https://launchpad.net/~xiphos-devel)?

**Comment by refdoc** [comment]
Am I???Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [crosswire/xiphos] Please update your translation tools (#862)From: LAfricain To: crosswire/xiphos CC: Peter von Kaehne ,Mention @refdoc you seem to be in the xiphos team on launchpad?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LAfricain in #862: @refdoc you seem to be in the xiphos team on [launchpad](https://launchpad.net/~xiphos-devel)?"}],"action":{"name":"View Issue","url":"https://github.com/crosswire/xiphos/issues/862#issuecomment-367014519"}}}

**Comment by LAfricain** [comment]
[Latest members](https://launchpad.net/~xiphos-devel): refdoc :)

**Comment by refdoc** [comment]
I will look what I can do. I am not sure I.really want to spend much time figuring this out. I might, if I have enough powers simply shut this down.So that no one else ends up similarly confused Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [crosswire/xiphos] Please update your translation tools (#862)From: LAfricain To: crosswire/xiphos CC: Peter von Kaehne ,Mention Latest members: refdoc :)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LAfricain in #862: [Latest members](https://launchpad.net/~xiphos-devel): refdoc :)"}],"action":{"name":"View Issue","url":"https://github.com/crosswire/xiphos/issues/862#issuecomment-367282658"}}}

**Comment by LAfricain** [comment]
Ok, but the sync would be very nice option! Gathering all Bible software in one place will save time with suggestions for translation.

**Comment by karlkleinpaste** [comment]
launchpad-based translation was a half-assed attempt several years ago by someone who is no longer a xiphos contributor, and never taken seriously by anyone, including that person. i don't doubt that what is found there is very old -- probably on the order of 5 or 6 years at the least.
personally, i find the idea of attaching myself or other developers or xiphos itself to Yet Another Neat Website To Do Secondary Stuff to be pretty annoying. (we get requests like this irregularly but not infrequently. see flatpak.) if someone were to make a serious, strong, personal commitment to completely take over all translation issues in such a way, i could be on board for it. absent that kind of commitment, my strong inclination is, as refdoc says, to shut it down to cancel the confusion factor that obviously results.

**Comment by karlkleinpaste** [comment]
LAfricain, if you're willing to take on responsibility for launchpad translation things, i believe we can arrange for you to get whatever privs are needed at both github (via me) and launchpad (via refdoc, i suppose). whether you personally can do so or not, i will close this report soon, with resolution either as letting launchpad be used properly, or as an effort abandoned.

**Comment by karlkleinpaste** [comment]
in fact, i'm just closing this now, especially because there is nothing within xiphos proper to be done about it -- it's all an external matter. a postmortem comment can be posted to give whatever detail is needed about whether anything will go forward with launchpad.
