### ISSUE TITLE
request: ANSI KJV2003 verse-per-line Bible .txt file for distribution please

### ISSUE THREAD

**Issue by jmichae3** [crosswire/xiphos#867]
ligatures could be rendered as 2-character adjacents.
2 versions could be made, one with italics and one without. italics is like /word set/
needed ASAP.
can you render them? great for fast Bible study and witnessing, and could be put into electronic Bibles.

**Comment by refdoc** [comment]
Your query is addressed at the wrong people. The developers of Xiphos create a programme which uses texts from CrossWire. We are providing an as much as possible correct semantically encoded KJV based in its entirety on the 1769 text. We do not provide any bastardised versions of any texts which you can find amply in other places. This is the official CrossWire stance on the matter. As such I personally (not speaking for CrossWire) find the KJV is essentially unintelligible for someone who has not grown up.with it, use of it in witnessing is ineffectual and based on the wrong premise that what sounds old is more venerable. That is of course a bizarre premise, considering that the translators of the time were aiming at using the current and common language of the people. Luther said of his endeavours to create a similarly venerated, but today equally unintelligible translation that his was created by "dem Volk aufs Maul schauen" - using colloquials of the time of common people. That the translations (both Luther and KJV) not only mirrored but also created common language at the time is of course part of the genius of the respective translatirs, but also reflects the high state of s spiritual openness of this time of reformation and renewal. But now you would require significantly more than.just spiritual openness to.understand these textsIf your concern is having a text which is based on the textus receptus, you will find several modern translations among our modules based on TR source.In HimPeterSent from my Huawei Mobile-------- Original Message --------Subject: [crosswire/xiphos] request: ANSI KJV2003 verse-per-line Bible .txt file for distribution please (#867)From: jmichae3 To: crosswire/xiphos CC: Subscribed ligatures could be rendered as 2-character adjacents.
2 versions could be made, one with italics and one without. italics is like /word set/
needed ASAP.
can you render them? great for fast Bible study and witnessing.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"request: ANSI KJV2003 verse-per-line Bible .txt file for distribution please (#867)"}],"action":{"name":"View Issue","url":"https://github.com/crosswire/xiphos/issues/867"}}}

**Comment by dmsmith** [comment]
This has nothing to do with Xiphos. If you wish, go to CrossWire.org for the KJV source and do with it as you wish, other than passing it off as an unadulterated text.

**Comment by jmichae3** [comment]
wow - no attempt at success from anybody.

**Comment by jmichae3** [comment]
I am external to xiphos, a developer. I was informed when I was looking at sword project that I could not work on these because I could not have access to the source. I am in the USA (WA).

does this mean I now have permission to obtain the KJV2003 module and use it?
or do I apply to them directly?
who do I purchase through to get it?

all I wanted to do someday was generate a KJV2003 KJV2003.txt file so I could do grep (etc) rapid searches. most applications are slow. I intend to readonly the file when I install it so it does not easily get modified.

**Comment by refdoc** [comment]
If you are a developer, then I would expect you to be able to read. Read the licenses.Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [crosswire/xiphos] request: ANSI KJV2003 verse-per-line Bible .txt file for distribution please (#867)From: jmichae3 To: crosswire/xiphos CC: Peter von Kaehne ,Comment I am external to xiphos, a developer. I was informed when I was looking at sword project that I could not work on these because I could not have access to the source. I am in the USA (WA).
does this mean I now have permission to obtain the KJV2003 module and use it?
or do I apply to them directly?
who do I purchase through to get it?
all I wanted to do someday was generate a KJV2003 KJV2003.txt file so I could do grep (etc) rapid searches. most applications are slow. I intend to readonly the file when I install it so it does not easily get modified.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jmichae3 in #867: I am external to xiphos, a developer. I was informed when I was looking at sword project that I could not work on these because I could not have access to the source. I am in the USA (WA).\r\n\r\ndoes this mean I now have permission to obtain the KJV2003 module and use it?\r\nor do I apply to them directly?\r\nwho do I purchase through to get it?\r\n\r\nall I wanted to do someday was generate a KJV2003 KJV2003.txt file so I could do grep (etc) rapid searches. most applications are slow. I intend to readonly the file when I install it so it does not easily get modified.\r\n\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/crosswire/xiphos/issues/867#issuecomment-370201386"}}}

**Comment by dmsmith** [comment]
I thought I was helpful. It is not an Xiphos issue. Karl was correct to close it. Go to CrossWire for the KJV source. I said this because I maintain it. Send email to support at crosswire dot org and I'll answer more fully.
