### ISSUE TITLE
No navbar in xiphos 4.1

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#897]
In the new compiled xiphos I have no navbar (for the navigation in the bible)
See the capture:
![xiphos_no_nav](https://user-images.githubusercontent.com/19690477/39959525-cc22be30-560a-11e8-9001-d15de2e4a9b7.png)

**Comment by karlkleinpaste** [comment]
there was a problem identified by someone else as 4.1.0 was released, where navbar disappears because of what amounts to a version gap of support as of 3.20.
the easy, one-shot fix for now is to edit ui/navbar_versekey.gtkbuilder to replace 3.20 with 3.18 (or whatever version of gtk3 you have installed; but older than 3.18 is nearly impossible).
reinstall (you don't need to rebuild entirely) and you should be fine.
changes have been made so that this is already handled when 4.1.1 is released.

**Comment by LAfricain** [comment]
Yes! Thanks.
Done
