### ISSUE TITLE
Windows 10 install fails: 4.1.0 32-bit installer

### ISSUE THREAD

**Issue by HnkGitHub** [crosswire/xiphos#899]
Platform: 64 bit Windows Professional Build 17677
Splash Screen opens, Main program opens. Splash screen never closes. Program never finishes loading. If you provide info for how to get debug report, would be willing to provide a better debug report.

Have to close program manually.

**Comment by Saved-by-Him** [comment]
I am having the same issue on Windows 8.1 64-bit System. 

Splash Screen opens, Main program opens. Splash screen never closes. Program never finishes loading... Same problem...

Xiphos version 4.0.7 is the last version to work correctly.

**Comment by karlkleinpaste** [comment]
sorry this has sat so long. this is apparently the same problem we've recently discussed elsewhere, where a first-time run of xiphos hangs for some indeterminate amount of time, but only on its very first run. it is apparently held up by something in the system, some registration issue as it begins the first time. thereafter it starts fine.
same as #865, #971, and others. closing because we need serious, new information in order to address this.
