### ISSUE TITLE
Drop down menu does not fully display in Fedora 28

### ISSUE THREAD

**Issue by jbbacher** [crosswire/xiphos#903]
![screenshot from 2018-06-21 08-53-26](https://user-images.githubusercontent.com/40466863/41724418-1f630a22-7533-11e8-8ac1-06358257b0eb.png)
As you can see in the screen shot the menu for books of the bible and longer chapter and verse lists display off to the left side of the screen and will not allow one to access the first 3 menu items.  Thanks for all the wonderful work you do.

**Comment by karlkleinpaste** [comment]
this was a reported error in previous versions of gtk w/wayland. it might have seen expression under Xorg as well, but mostly a wayland interaction problem. i'm not going to pretend to understand why that matters. regardless, however, we haven't heard a new report of this in a long time. closing. if it needs to be re-opened because of new evidence of a problem, we can. in general, everything about the geometry of pulldown displays, from size to button packing at top & bottom to placement on the screen is the responsibility of the toolkit, not xiphos itself.
