### ISSUE TITLE
Add the comma as a chapter and verse separator in the Ref box

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#904]
Currently if you copy/paste a French ref (e.g. Jn 1,23) in the Ref box, it will search Jn 1,1, because Xiphos doesn't recognize the French separator between chapter and verse (comma). We need to use only ":" if we will navigate. 
I should be nice if all separator can be used.

**Comment by karlkleinpaste** [comment]
not sure what "the Ref box" is, but...

xiphos doesn't control this. all navigation references are blind strings to xiphos, content that xiphos merely hands off to sword for expansion and reference. whatever you type in the location bar (if that's what you meant) or in a bookmark reference is copied uncritically by xiphos, handed to sword for normalization and reference discovery. so you can type a lot of different book abbreviations and peculiar references and xiphos will eat them happily and hope for the best in what comes back from sword. you can see this if you type OSIS-style references, such as "jn.1.23", which will come back normalized as "John 1:23". sword will normalize a lot of book abbreviations ('g' by itself is treated as Genesis, 'j' as Joshua, and so on) and the chapter:verse reference is then interpreted within the book that sword determined (read: guessed) you meant.

what you're asking for is a more in-depth, locale-sensitive reference parser. for that, you need to ask for an update to sword, not xiphos. i'm not sure that's possible, given sword's architecture today, especially because certain multi-verse references depend on dashes, commas, and semicolons now. for example, you can store a bookmark reference in xiphos for "Gen 3:15,16,19; 1Cor 9:15-19" which, when this is clicked in xiphos bookmarks, will generate (via request to sword) a verse list consisting of 3 verses in Gen 3 and 5 verses in 1Cor 9. in doing this, note that sword already has an idea of how it should interpret comma (and dash and semicolon) in this context, and again xiphos had nothing to say about it other than to accept the user's strings and store them in the bookmarks structure. you're asking that sword understand a 2nd meaning of comma, which is likely to be contextually hard and unreliable.

**Comment by LAfricain** [comment]
I proposed a patch for sword.
