### ISSUE TITLE
jude 20 fails, need to use jude 1:20

### ISSUE THREAD

**Issue by TomSullivanInUSA** [crosswire/xiphos#905]
Using Debian 9, XFCE 4.12, Xiphos 4.1.0 (gtk3 webkit1). Not sure if this is feature enhancement or bug. Type "jude 20" in either regular or parallel view and get Rev. 19:1. Type jude 1:20, and get it OK. Obadiah fails also.

**Comment by greg-hellings** [comment]
This is the correct and intentional behavior of the SWORD engine that underlies Xiphos and parses the references.

**Comment by TomSullivanInUSA** [comment]
OK, I understand. Let us make it a feature request then to enhance usability. This would be a matter of Xiphos interposing a "1:" for single-chapter books so that users doing the natural thing will get their passage. Xiphos staff, of course, will have to decide if it is worth it.

**Comment by refdoc** [comment]
No. Make it please a bug or feature request in sword. That is the right place. PeterSent from my Huawei Mobile-------- Original Message --------Subject: Re: [crosswire/xiphos] jude 20 fails, need to use jude 1:20 (#905)From: TomSullivanInUSA To: crosswire/xiphos CC: Subscribed OK, I understand. Let us make it a feature request then to enhance usability. This would be a matter of Xiphos interposing a "1:" for single-chapter books so that users doing the natural thing will get their passage. Xiphos staff, of course, will have to decide if it is worth it.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TomSullivanInUSA in #905: OK, I understand. Let us make it a feature request then to enhance usability. This would be a matter of Xiphos interposing a \"1:\" for single-chapter books so that users doing the natural thing will get their passage. Xiphos staff, of course, will have to decide if it is worth it."}],"action":{"name":"View Issue","url":"https://github.com/crosswire/xiphos/issues/905#issuecomment-401069595"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/crosswire/xiphos/issues/905#issuecomment-401069595",
"url": "https://github.com/crosswire/xiphos/issues/905#issuecomment-401069595",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [crosswire/xiphos] jude 20 fails, need to use jude 1:20 (#905)",
"sections": [
{
"text": "",
"activityTitle": "**TomSullivanInUSA**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@TomSullivanInUSA",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"crosswire/xiphos\",\n\"issueId\": 905,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/crosswire/xiphos/issues/905#issuecomment-401069595"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 351154530\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by TomSullivanInUSA** [comment]
Y'all:

I understand the logic of fixing it is Sword. I leave it to you folks to 
do as best you see fit.

Many thanks for all you do on this stuff.

Tom

Tom@SullivanInUSA.com
FAX: 815-301-2835
---------------------
Great News!
God created you, owns you and gave you commands to obey.
You have disobeyed God - as your conscience very well attests to you.
God's holiness and justice compel Him to punish you in Hell.
Jesus Christ became Man, was crucified, buried and rose from the dead
as a substitute for all who trust in Him, redeeming them from Hell.
If you repent (turn from your sin) and believe (trust) in Jesus Christ,
you will go to Heaven. Otherwise you will go to Hell.
Warning! Good works are a result, not cause, of saving trust.
More info is at www.esig.beforgiven.info
Do you believe this? Copy this signature into your email program
and use the Internet to spread the Great News every time you email.

On 06/29/2018 09:33 AM, Peter von Kaehne wrote:
> No. Make it please a bug or feature request in sword. That is the right 
> place. PeterSent from my Huawei Mobile-------- Original Message 
> --------Subject: Re: [crosswire/xiphos] jude 20 fails, need to use jude 
> 1:20 (#905)From: TomSullivanInUSA To: crosswire/xiphos CC: Subscribed 
> OK, I understand. Let us make it a feature request then to enhance 
> usability. This would be a matter of Xiphos interposing a "1:" for 
> single-chapter books so that users doing the natural thing will get 
> their passage. Xiphos staff, of course, will have to decide if it is 
> worth it.
> 
> —You are receiving this because you are subscribed to this thread.Reply 
> to this email directly, view it on GitHub, or mute the thread.
>
 {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub
 
>
 repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open
 
> in 
>
 GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TomSullivanInUSA 
> in #905: OK, I understand. Let us make it a feature request then to 
> enhance usability. This would be a matter of Xiphos interposing a \"1:\" 
> for single-chapter books so that users doing the natural thing will get 
> their passage. Xiphos staff, of course, will have to decide if it is 
> worth it."}],"action":{"name":"View 
>
 Issue","url":"https://github.com/crosswire/xiphos/issues/905#issuecomment-401069595"}}}
