### ISSUE TITLE
jude 20 fails, need to use jude 1:20

### ISSUE THREAD

**Issue by TomSullivanInUSA** [crosswire/xiphos#906]
Using Debian 9, XFCE 4.12, Xiphos 4.1.0 (gtk3 webkit1). Type "jude 20" in either regular or parallel view and get Rev. 19:1. Type jude 1:20, and get it OK. Obadiah fails also.

Greg Hellings replied:
This is the correct and intentional behavior of the SWORD engine that underlies Xiphos and parses the references.

My response to Greg: (Sorry, I do not know how to re-open a closed issue.)
OK, I understand. Let us make it a feature request then to enhance usability. This would be a matter of Xiphos interposing a "1:" for single-chapter books before sending to the SWORD engine so that users doing the natural thing will get their passage. Xiphos staff, of course, will have to decide if it is worth it. (This is a resubmission of a closed issue, but I will not be a pest and reopen it again if the feature is decided against.:-) )

**Comment by dmsmith** [comment]
JSword does what you think it should. It also handles specifying chapter and verse. It disambiguates in favor of a verse number when it is a single chapter book context. When it is not a single chapter book context, it decides a single number is a chapter. The real complexity comes with book intros (0:0) and chapter intros (1:0). Only mention it because what you want is doable.

I don’t think this belongs in Xiphos, but in SWORD. That’s where the verse parser is.

In Him,
	DM
