### ISSUE TITLE
Date in devotional windows is not translated

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#934]
The date in the devotional windows is not translated. Is it possible to do it?
![devotional](https://user-images.githubusercontent.com/19690477/55227845-cdfb4500-5218-11e9-995b-7072ce9d70d8.png)

**Comment by domcorbex** [comment]
The devotional window should also have an option for displaying the date depending on the calendar type: Julian, Gregorian, Hebrew, Persian, Ethiopian, Coptic...

**Comment by LAfricain** [comment]
With the last commits I have th translation of the month, great! But In French we write first the number of the day and after the number of the months, and the year. 
Is it possible to do this? And the displaying the day of the week can be also a great thing.
Thank you.

**Comment by greg-hellings** [comment]
Are you referring to the text entry box "12.25"? Unfortunately that's the actual module key and Sword doesn't provide a way to localize that.

**Comment by karlkleinpaste** [comment]
the type of calendar ... well, it's operating on your system's sense of "today," whatever that is. if your system is actually operating on the ethiopian calendar...i'm alarmed and impressed.

but as greg said, that blob is a module key, in the same way that a certain word is a dictionary key, because in fact the digits-and-dot MM.DD are the "word" that keys into a devotional "dictionary." that is, a devotional is just a dictionary with the "devotional" attribute in the .conf, with a certain key format known by convention.

absent a major sword change for what the sense of a devotional is, i can't do a thing with it.

**Comment by LAfricain** [comment]
I'm not speaking about the box entry, but about the text displayed below look the picture, Avril 16, should be 16 avril or better Jeudi 16 avril:
![devotional](https://user-images.githubusercontent.com/19690477/79492882-eeaf5c00-8020-11ea-85b0-b95496b8a781.png)

**Comment by karlkleinpaste** [comment]
i've had a late thought on this. it's too late for today's 4.2.0, but i will see if there's something i can do with it soon. it depends on system-level support for date formatting, which i think exists and could be used here. i'll leave it closed (because i'm not certain what i'm thinking can be done) but you might see a post-closure update in the near future.

**Comment by LAfricain** [comment]
Ok Karl, thank you! I'll wait the next release.

**Comment by LAfricain** [comment]
@karlkleinpaste  remember?
