### ISSUE TITLE
I18n improvements

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#935]
I'm currently translating xiphos to it (and a few part in French).
1. In the file src/gtk/about_sword.c line 142, We have this text:
```
See the manual for details.
(Preferences -> BibleSync Settings and Interface -> Keyboard Shortcuts.)
```
But it's not easy to understand. If I go in Preferences I can't find BibleSync Settings and Interface -> Keyboard Shortcuts. And even for the help. Where to find this Keybord shortcuts

2. What the meaning of Combo?

**Comment by refdoc** [comment]
One of the problems may well 've that the original manual needs updating too... PeterSent from my Huawei Mobile-------- Original Message --------Subject: [crosswire/xiphos] I18n question (#935)From: LAfricain To: crosswire/xiphos CC: Subscribed I'm currently translating xiphos to it (and a few part in French).
In the file src/gtk/about_sword.c line 142, We have this text:
See the manual for details.
(Preferences -> BibleSync Settings and Interface -> Keyboard Shortcuts.)

But it's not easy to understand. If I go in Preferences I can't find BibleSync Settings and Interface -> Keyboard Shortcuts. And even for the help. Where to find this Keybord shortcuts

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"I18n question (#935)"}],"action":{"name":"View Issue","url":"https://github.com/crosswire/xiphos/issues/935"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/crosswire/xiphos/issues/935",
"url": "https://github.com/crosswire/xiphos/issues/935",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by LAfricain** [comment]
> One of the problems may well 've that the original manual needs updating too..

Maybe I can help. Please give me the instructions.

**Comment by LAfricain** [comment]
I found:
Save AS
Maybe:
Save As… should be better?

**Comment by LAfricain** [comment]
I will report here some minor incoherence in the text. 
1. sometimes the contextual help when the mouse is on a place ends with a . sometimes no. Please remove all the points:
```
#: ../src/gtk/search_sidebar.c:258
msgid "Open the separate Advanced Search dialog."
: ../ui/prefs.glade.h:95 ../ui/prefs.gtkbuilder.h:95
If you have set a preferred daily devotion module, its entry for today will be shown at startup.
#: ../ui/prefs.glade.h:121 ../ui/prefs.gtkbuilder.h:121
msgid "Parallel window can use alternating foreground/background."
#: ../ui/prefs.glade.h:36 ../ui/prefs.gtkbuilder.h:35
msgid "Select the mode in which BibleSync should operate."
#: ../ui/prefs.glade.h:38 ../ui/prefs.gtkbuilder.h:38
msgid "Disable BibleSync."
```
And all the biblesync dialog.

For this entry:
```
Enter a Verse reference in Book 1:1 format and press Return
```
I propose to add:
```
Enter a Verse reference in Book 1:1 (or 1.1) format and press Return
```
In the windows About Xiphos, Xiphos is without capital letter: **x**iphos

This line is not localised:
src/gtk/main_menu.c:669:	dialog = gtk_file_chooser_dialog_new("Save Session",

This line is not display in the locale (but it is translated):
`src/main/parallel_view.cc:61:SWBuf unknown_parallel = N_("Unknown parallel module: ");`

If you want I can do the job and push it. Please confirm it.

**Comment by domcorbex** [comment]
> This line is not localised:
> src/gtk/main_menu.c:669: dialog = gtk_file_chooser_dialog_new("Save Session",

Fixed in commit 43ffa59

**Comment by domcorbex** [comment]
> This line is not display in the locale (but it is translated):
> src/main/parallel_view.cc:61:SWBuf unknown_parallel = N_("Unknown parallel module: ");
Fixed in commit 8192fd6

**Comment by LAfricain** [comment]
Thanks Dom,
For the other issue may I do the job or you'll do it?

**Comment by domcorbex** [comment]
Hi L'Africain!
Do it!

**Comment by LAfricain** [comment]
OK.
Done. I will do a merge request.
But I don't found the windows "About xiphos", without capital letter: xiphos

**Comment by LAfricain** [comment]
Two minor places not i18n:

![Fonts](https://user-images.githubusercontent.com/19690477/55705153-64c8be00-59de-11e9-9ed2-a6a48a20031f.png)
(none Language and cancel)
And:
![advanced-search](https://user-images.githubusercontent.com/19690477/55705191-8164f600-59de-11e9-8ab8-774c73bd8b39.png)
(Old/New testament and Sample Module list)

**Comment by LAfricain** [comment]
Currently we have two folders help and mhelp. The po file are not the same. Please clean it, or give indication for what need to be translated. I waste time to translate firs help ;)
Thanks.

**Comment by LAfricain** [comment]
`Downloading` is not i18n.

**Comment by domcorbex** [comment]
> Downloading is not i18n.
For this particular string, if I remember well, it comes from Sword.
