### ISSUE TITLE
ftp.xiphos.org unresponsive

### ISSUE THREAD

**Issue by rogerfranz** [crosswire/xiphos#937]
Hate to bring this up again (prior issues 459, 507), but the ftp.xiphos.org repository is not responding. Is there a mirror for the content?

**Comment by karlkleinpaste** [comment]
there is no mirror that i'm aware of, other than my personal Dropbox from which it is maintained.
ftp.xiphos.org is a very small VSP at a dallas colo. its current uptime is over 100 days.

in the last 2+ years, it has rebooted only a handful of times. if you find it AWOL for some time, it is actually far more likely that routing between you and it glitched, rather than that the machine was down. it delivers roughly 15G/day via ftp and another 10G/day via https.

$ last reboot
reboot   system boot  2.6.32-042stab14 Thu Dec 26 12:14 - 12:36 (113+23:22)
reboot   system boot  2.6.32-042stab13 Thu Nov 21 16:41 - 12:36 (148+18:54)
reboot   system boot  2.6.32-042stab13 Sun Oct 27 15:12 - 12:36 (173+21:23)
reboot   system boot  2.6.32-042stab13 Wed Jun 19 07:04 - 12:36 (304+05:31)
reboot   system boot  2.6.32-042stab13 Wed May  8 07:37 - 07:04 (41+23:27)
