### ISSUE TITLE
The rawCom4/zCom4 ModDrv does not work

### ISSUE THREAD

**Issue by tianmiaohu** [crosswire/xiphos#942]
For a custom commentary module, book intro length is greater than 64K and is cutoff if ModDrv set to zCom.  I managed to get Xiphos 4.1.0 installed on Debian via unstable repo.  But to my disappointment, the zCom4 ModDrv does not work.  I got blank pages after blank pages in the commentary view.  When I switched back to zCom ModDrv, it works fine but the book intro got cutoff.

Also tried RawCom4 and Xiphos crashed upon open.

**Comment by refdoc** [comment]
This would be a libsword matter, not Xiphos, so if my advice below is
not applicable or not working, please report it there, not here. 

Is the module actually built with zCom4? It would need to be in order
to work. If you try to read a zCom module with zCom4 it will fail, of
course.

Peter

**Comment by tianmiaohu** [comment]
I used the default libsword from Debian unstable source.  Not sure if it has zCom4.  According to crosswire website doc, zCom4 was added to 1.8 SWORD, not 1.7.  So I assume that it should be enabled by default.  

The Xiphos behavior for zCom4 is different from rawCom4.  When I use rawCom4, Xiphos just crashed.  Should I report a separate issue on that?  Does rawCom4 require something underlying in libsword?

There is just not enough doc to find compile instructions on zCom4, or xs and bzip2 compression for that matter.  In Debian both xs and bzip2 are not enabled.

GenBook does not suffer this 64K issue.  I ended up make a GenBook for the book intro content.  So I am happy so far.

**Comment by greg-hellings** [comment]
On Mon, Apr 15, 2019 at 4:02 PM tianmiaohu <notifications@github.com> wrote:

> I used the default libsword from Debian unstable source. Not sure if it
> has zCom4. According to crosswire website doc, zCom4 was added to 1.8
> SWORD, not 1.7. So I assume that it should be enabled by default.
>
Do you know what version of libsword you got from the Debian archives?
There should be an apt command that could tell you.

> The Xiphos behavior for zCom4 is different from rawCom4. When I use
> rawCom4, Xiphos just crashed. Should I report a separate issue on that?
> Does rawCom4 require something underlying in libsword?
>
zCom4 support would depend on the version of libsword you have. The fact
that you're getting blank and not crashing is a good sign that you are
probably using libsword 1.8 and it has support for zCom4. As Peter has
alluded to, though, you must invoke the osis2mod (or imp2mod or vpl2mod or
whatever command you are using to create the module) with different
parameters to actually create a module with zCom4. You can't just change
the conf file on an already built module. imp2vs needs to be invoked with
the "-4" switch. osis2mod would need to be invoked with the option "-s 4".

The "4" in the name refers to the size of one of the entries in the index
file. Specifically, the index includes an entry for each verse including
location in the data file where the verse begins and the length of the
entry. zCom uses a 2 byte field for length (on modern computers this is 16
bits, meaning a total of 64KB of compressed data). zCom4 uses a 4 byte
field for length (giving 32 bits, for a maximum of a 4GB entry per
reference).

Changing the conf file from zCom to zCom4 without recreating the module
with the appropriate options would just mean that libsword is reading the
index file incorrectly, and therefore is gathering the incorrect amount of
data from the module files. This will lead to incorrect or missing values
and possibly application instability. You need to not only change the conf
file, but you need to run the importer utility across the source document
with the appropriate flags.

> There is just not enough doc to find compile instructions on zCom4, or xs
> and bzip2 compression for that matter. In Debian both xs and bzip2 are not
> enabled.
>
xz and bzip2 would need to be enabled at compile time. If Debian is not
building libsword with those options, then you will not be able to use them.

> GenBook does not suffer this 64K issue. I ended up make a GenBook for the
> book intro content. So I am happy so far.
>
Correct, GenBook does not have entry size limits nearly as strict as
commentaries and Bibles do. I believe it defaults to 4GB limits per entry.
But it suffers from not having the ability to pair with a Bible because it
can't be referenced by chapter and verse.

--Greg

**Comment by tianmiaohu** [comment]
The "4" parameter of imp2vs is the key.  I was able to successfully create a RawCom4 commentary module with this parameter.  It displays correctly in Xiphos.  Beautiful!

However, I still cannot get zCom4 to work.  When I try to use the "z" parameter with the "4" parameter, I get the following output from imp2vs:
imp2vs: Cannot specify both -z and -4
I tried imp2vs from both Debian and the Windows version that comes with Xiphos 4.1.0.  Both gave the same error.

I really appreciate your prompt and kind assistance in this matter!  I consider this issue has been resolved.

I hope that you can take a look at issue 940.  For large commentary or book, it will be really helpful that Xiphos can record the last viewing position of the entire user reading history.  This way when the user goes back to the document, he//she does not need to scroll up/down to find that position.

**Comment by tianmiaohu** [comment]
One more comment:
I tried to use mod2zmod tool to convert RawCom4 into zCom4.  It did not work.  Some chapters show up.  Some do not.  Book heading does not show up.

This will be my last effort on this issue.  RawCom4 is the way to go.
