### ISSUE TITLE
Shortcuts work only in English keyboard and without caps lock!

### ISSUE THREAD

**Issue by Bohooslav** [crosswire/xiphos#948]
Shortcuts work only in English keyboard and without caps lock. You need add support for other languages. I'm on fedora 29/30, Gnome 3.

**Comment by refdoc** [comment]
Support can be added in each language in the translation files. It requires a good knowledge of the language, good knowledge of computer conventions in that language and good knowledge of the programme so that no duplicates occur in any given menu. As we as a group speak mostly only English only few languages other than English have this added. If you wish to add it for your language, you are most welcome. Please look into the source files under ./po and open the relevant file with a programme like poedit and fix it. Thank you so much for your contribution in advance!!Sent from my Huawei Mobile-------- Original Message --------Subject: [crosswire/xiphos] Shortcuts work only in English keyboard and without caps lock! (#948)From: Богуслав To: crosswire/xiphos CC: Subscribed Shortcuts work only in English keyboard and without caps lock. You need add support for other languages. I'm on fedora 29/30, Gnome 3.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/crosswire/xiphos/issues/948?email_source=notifications\u0026email_token=AADY6C5MGDZVE7KKP2TVVRTPVY7O3A5CNFSM4HNSGO42YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GUKJURQ",
"url": "https://github.com/crosswire/xiphos/issues/948?email_source=notifications\u0026email_token=AADY6C5MGDZVE7KKP2TVVRTPVY7O3A5CNFSM4HNSGO42YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GUKJURQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
