### ISSUE TITLE
Windows version crashes after opening

### ISSUE THREAD

**Issue by ghost** [crosswire/xiphos#953]
Title says it all. Installed it, added some modules then closed it. Today I wanted to open it but it keeps crashing. I cant click through anything. 
I dont have any AV apart from Windows Defender. Windows 10 64-bit with latest updates

Thank you for your time

**Comment by WHairstonLOI** [comment]
I've been having exactly the same issue for several months. Windows Defender, Windows 10 v1903 x64 with latest patches.

I start the program and before the screen can fully load the text of the last Bible chapter I was in, it crashes. Event Viewer shows Event ID 1000 with:

Faulting application name: xiphos.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: libwebkitgtk-1.0-0.dll, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000000000085a38f
Faulting process id: 0x2f7c
Faulting application start time: 0x01d5bb9ee6efef5b
Faulting application path: C:\Program Files (x86)\CrossWire\Xiphos\bin\xiphos.exe
Faulting module path: C:\Program Files (x86)\CrossWire\Xiphos\bin\libwebkitgtk-1.0-0.dll
Report Id: b0d02dd0-f9f8-40ad-90a2-2a4dd454e47c
Faulting package full name: 
Faulting package-relative application ID: 

Thanks for any help you can provide!

**Comment by karlkleinpaste** [comment]
apologies for letting this sit, i'm coming back from the dead...

on the win10 machines i have at hand, i don't see any problem at startup. what concerns me most is that the fault is occurring (per info above) in the webkit module, which is not something we build ourselves, rather it's a utility library for text display that just comes along for the ride.

just now on my wife's win10 laptop, she installed and ran it three times. first time, it asked for initial module installation. did that, closed. re-opened, it paused a while (a problem we've failed to diagnose for quite some time, because it happens exactly once for any machine, something to do with registry), then displayed normally. third time, just started normally. no problem seen.

if there was any further info, i'd be pleased to have it. do you even know what modules xiphos would have been attempting to display?

**Comment by WHairstonLOI** [comment]
Hi Karl,

Thanks for the follow-up.

It’s the strangest thing: I hadn’t tried to start the program since I originally submitted the problem report. Tonight, it started right up and stayed functional! Maybe a Windows update during the past few months has corrected the problem? It certainly wouldn’t be the first time a Windows update has fixed a mysterious problem. In any case, this issue seems to have resolved itself for now.

Thanks and blessings!
Warren

**Comment by karlkleinpaste** [comment]
lacking any corroboration other than things having improved, i'm closing this. feel free to open something new if it should re-surface.
