### ISSUE TITLE
arrows by book name confusing

### ISSUE THREAD

**Issue by dosxga** [crosswire/xiphos#970]
I get confused from the arrows by the book name and find them confusing.  I am used to berean bible and esword works ok.   
When I want to go up in the text and it goes down, and am left handed.   Any suggestions instead of using arrow buttons that I have been trying?  --  It looks like the left right arrows do what the first (on the left up down arrows do)
Thanks for making this and help anyone gives. PTL

**Comment by egeiro** [comment]
When the focus is on the Bible window shift-p goes to the previous book and shift-n to the next book.
Equally pressing 'p' takes to you the previous chapter and 'n' to the next chapter.
Control-p moves focus to the previous verse and control-n to the next verse.

Using these means you can avoid pressing the arrows by the book name.

**Comment by karlkleinpaste** [comment]
@egeiro's suggestions are worthwhile, and see the manual section on keyboard shortcuts.

generally, the problem is a semantic conflict that some perceive, between seeing chapter/verse numbers go "up" when in fact they really go "farther" into the text. the BCV pulldowns all display in normal sorted order, where "up" numerically is "down" in the list, and hence "farther" into the text.
