### ISSUE TITLE
Xiphos is almost unusable on smaller screen devices, phones.

### ISSUE THREAD

**Issue by programmin1** [crosswire/xiphos#981]
When I install Xiphos on the Librem 5 emulator, it is really hard to use because of the required screen width of this program. See the screenshots and you'll know what I mean. The title bar has to be moved left and right to see the check box to install, then go down and tap the install. and then view doesn't look right, with half the screen the left sidebar.

![Screenshot from 2020-01-04 00-09-36](https://user-images.githubusercontent.com/1295242/71762707-b3c95400-2e87-11ea-8362-6d9f978107b1.png)

![Screenshot from 2020-01-04 00-14-13](https://user-images.githubusercontent.com/1295242/71762709-b9bf3500-2e87-11ea-842c-cd5fd2998175.png)

I wrote up a blog post on how I reworked a GTK app for use on the Librem [here](https://howtotrainyourrobot.com/building-an-amateur-radio-app-for-librem-phone-part-3/). This is going to be more important as more and more phones use Linux desktop applications - the Librem 5, the PinePhone... probably others.

**Comment by DavidHaslam** [comment]
**Xiphos** was designed for larger displays than most smart phones have.

There are several other SWORD (or JSword) based front-end Bible study apps specifically intended for smart phones and tablets.
- **PocketSword** for iOS & iPadOS
- **And Bible** for AndroidOS
- **Bishop** (_aka_ The SWORD Project) for both
- **BibleTime Mini**
- **Ezra Project**

etc.

**Comment by karlkleinpaste** [comment]
while i appreciate the desire to see xiphos in use in more places, its fundamental design habits since inception fully 2 decades ago have revolved around systems other than small tablets and smaller phones. it's a full-featured, heavy duty, bells-and-whistles application (just look at its memory footprint sometime when it's running, you'll be alternately impressed or appalled) intended for enough screen real estate to have a lot of material to work with at one time. just the idea that xiphos presumes that the user needs to have all of a bible, commentary, and dictionary simultaneously open renders the idea of "let's use a tiny screen" out of normal bounds. over time, i've already reduced its minimum screen size beyond what i personally think is reasonable, given its intended usage patterns. sorry, i'm not going to put further effort into smallification.
